version: '3'

services:
  springboot:
    container_name: spring-dev
    image: jedero/backend:latest
    ports:
      - 8080:8080
    environment:
      SPRING_PROFILES_ACTIVE : dev-env
    networks:
      - my_network

networks:
  my_network:
    driver: bridge