version: '3'

services:
  springboot:
    container_name: spring-dev
    image: jederosite/backend:latest
    ports:
      - 8080:8080
    environment:
      SPRING_PROFILES_ACTIVE: dev-env
    networks:
      - jedero_network

  redis:
    container_name: redis-jedero
    hostname: redis
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - jedero_network

networks:
  jedero_network:
    driver: bridge